baseURL = 'http://akalientess.com/'
relativeurls = true
languageCode = 'en-us'
title = 'Akalientess'
disableKinds = ["section"]
[permalinks]
    list-of-projects = "/:filename"
    pattern-library = "/:filename"