baseURL = 'https://akalientess.com/'
relativeurls = true
languageCode = 'en-us'
title = 'AkaLientesS'
disableKinds = ["section"]
[permalinks]
    list-of-projects = "/:filename"
    pattern-library = "/:filename"
    akali = "/:filename"
    katarina = "/:filename"
    yasuo = "/:filename"